export * from './create-clinics-service'
export * from './update-clinics-service'
export * from './delete-clinics-service'
export * from './get-clinics-service'
export * from './get-clinics-by-id-service'
