export * from './base-repository'
export * from './doctor-repository'
export * from './secretary-repository'
export * from './patient-repository'
export * from './admin-repository'
export * from './clinic-repository'
export * from './doctor-schedule-repository'
