export * from './create-clinics-controller'
export * from './update-clinics-controller'
export * from './delete-clinics-controller'
export * from './get-clinics-by-id-controller'
export * from './get-clinics-controller'
