version: "3"

services:
  api:
    image: yansoares/doctor-api:(production/development)
    environment:
      JWT_SECRET: ${JWT_SECRET}
      JWT_SECRET_REFRESH_TOKEN: ${JWT_SECRET_REFRESH_TOKEN}
      JWT_SECRET_EXPIRES_IN: ${JWT_SECRET_EXPIRES_IN}
      JWT_SECRET_REFRESH_TOKEN_EXPIRES_IN: ${JWT_SECRET_REFRESH_TOKEN_EXPIRES_IN}
      MYSQL_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    expose:
      - 3000
    ports:
      - 3000:3000
    depends_on:
      - mysql
    networks:
      - example-doctors-office-api-network

  mysql:
    platform: linux/x86_64
    image: mysql:8.0-debian
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    expose:
      - 3306
    ports:
      - 3306:3306
    networks:
      - example-doctors-office-api-network

# Network necessariamente precisa ser com driver bridge
networks:
  example-doctors-office-api-network:
    driver: bridge
