export * from './create-secretaries-controller-factory'
export * from './update-secretaries-controller-factory'
export * from './delete-secretaries-controller-factory'
export * from './get-secretaries-controller-factory'
export * from './get-secretaries-by-id-controller-factory'
