export * from './create-clinics-controller-factory'
export * from './update-clinics-controller-factory'
export * from './delete-clinics-controller-factory'
export * from './get-clinics-controller-factory'
export * from './get-clinics-by-id-controller-factory'
